meta_product_name: "Treep"
meta_title: "Treep - Stop wasting time planning trips."
meta_description: "With Treep, stop wasting time planning trips. Gather all the potential points of interest along the way, visualize the different itineraries and enhance communication with travelers to build a trip tailored to their dreams."
meta_image: "cover.png"                       # should exist in `app/assets/images/`
twitter_account: "#"   # required for Twitter Cards
